### ISSUE TITLE
Pause option

### ISSUE THREAD

**Issue by Milchreis** [Milchreis/p5.tween#5]
Idea:
Use `tween.pause()` to pause the motion and `tween.resume()` to continue.

**Comment by ffd8** [comment]
Could also be nice to have a method for restarting the tween process, something like: 
- `tween.restart()`
- `tween.step(0)` (or `tween.jump(0)` if going immediately to those values)

tried using a `mousePressed` to restart the motion.. but found one can only reset the added steps..

**Comment by Milchreis** [comment]
Hi @ffd8 

thank you for your input. I added the restart-method with version 1.1.0 now. A step method is much harder, because all previous steps have to calculated or simulated. This could be a new issue 😊
