### ISSUE TITLE
Cant use p5.tween with node

### ISSUE THREAD

**Issue by pedrolaxe** [Milchreis/p5.tween#6]
Hi,

I am trying to use p5.tween on a node project, but when I try import, it gives me this error:

```js
p5.min.js:3 Did you just try to use p5.js's registerMethod() function? If so, you may want to move it into your sketch's setup() function.

For more details, see: https://github.com/processing/p5.js/wiki/p5.js-overview#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup
p5.tween.js:177 Uncaught TypeError: Cannot read properties of undefined (reading 'registerMethod')
    at eval (p5.tween.js:177:25)
    at eval (p5.tween.js:178:7)
    at eval (p5.tween.js:179:3)
    at Object../node_modules/p5.tween/dist/p5.tween.js (vendor.js:2417:1)
```

It is happening because p5.tween tries to invoke the p5.prototype before p5 is defined.

I tryied many different approaches.
Could please help me showing an example how to use p5.tween on a node project?

Thank you!

**Comment by Milchreis** [comment]
Hi pedro,

thank you for reporting. I am not sure, but I think p5js is not working with nodejs. It's build to run in browser (client-side) and not server-side. 

Maybe this is the reason, why p5.tween is not loaded correctly.

**Comment by pedrolaxe** [comment]
Thanks!
