### ISSUE TITLE
0 as target breaks

### ISSUE THREAD

**Issue by ffd8** [Milchreis/p5.tween#7]
Awesome library! Testing it out and discovered that passing `0` as a target breaks. Maybe it's intended or an issue with the interpolation function? Tried having a [shape walk around the border of window](https://editor.p5js.org/ffd8/sketches/uXkOtFmST), and was confused why it wasn't returning to coordinates of `0, 0`... wondered if it was relative, since `-width` worked (was going faast in neg space).. and learned that changing to `1` worked as expected. While testing, discovered that indeed all values are absolute.. but could also be interesting to have a `relative` mode, tweaking current value.

```
let ms = {
  x: 0,
  y: 0,
  w: 50,
};

p5tween = p5.tween.manager
    .addTween(ms)
    .addMotions(
      [
        { key: "x", target: width },
        { key: "y", target: 0 },
        { key: "w", target: 200 },
      ],
      1000
    )
    .addMotions(
      [
        { key: "x", target: width },
        { key: "y", target: height },
        { key: "w", target: 1 }, // 0 breaks
      ],
      1000
    )
    .addMotions(
      [
        { key: "x", target: 1 }, // 0 breaks
        { key: "y", target: height },
        { key: "w", target: 300 },
      ],
      1000
    )
    .addMotions(
      [
        { key: "x", target: 1 }, // 0 breaks
        { key: "y", target: 1 }, // 0 breaks
        { key: "w", target: 50 },
      ],
      1000
    );
```

**Comment by Milchreis** [comment]
hi @ffd8 

thank you for your feedback and the detailed code snippet in p5 editor :-)
I did some debugging and find the problem: 
Before each action is executed an if-statement checks the given target to be true, but `action.target = 0` is not true for JS :-/

It's a basic JS beginner mistake 🙈. Thank you for the issue and with the next release it will work as expected 😊

**Comment by ffd8** [comment]
@Milchreis - welcome and awesome it's a quick fix. 

ahaa, fun feature/bug of JS playing with the var as number/boolean. 
Should blame the language.. not the coder...
