### ISSUE TITLE
events like onEnd() or similar?

### ISSUE THREAD

**Issue by ffd8** [Milchreis/p5.tween#8]
Many thanks for this library! It's an awesome way for some of my students to move shapes in specific paths (ie creating letter forms from moving png's), but when trying to switch from one motion path to another, failed to find an event that sent a ping when a tween was finished – perhaps it doesn't exist yet? Had you considered having eventListeners or something similar that would call a function when the tween finished? Found a kinda workaround by asking constantly in the draw if the tween was active, then reacting when not, [example sketch](https://editor.p5js.org/ffd8/sketches/Bsn1Am2D9). Perhaps a few methods would be helpful to have:
- `onEnd()`
- `onLoop()`

Noo idea how to implement such a thing, but would help create some complex tween sequences.
Of course one could just add LOTS of motions for all their steps, but then I couldn't find a 'jump to' motion... and the student wanted to organize their motions per letter like 'T', 'M' etc...

**Comment by Milchreis** [comment]
hi @ffd8

thanks for the question and the interest in my tween library 😊 I'm glad to hear that there are people using my software. Currently there is no event handler or listener for these actions, but this is a very good idea. 
Give me some time and I will try to implement this.

**Comment by Milchreis** [comment]
Ok, that was fortunately quite simple 😊 
Here is a sketch as example. I have implemented the onEnd and onLoop listener.
[sketch](https://editor.p5js.org/Milchreis/sketches/7lIxFsbWM)

greetings to the students 😊
